### PR TITLE
Initial structure

### PR DESCRIPTION
**Pull request by Voklen**
I made sure to make it use OOP just as you like. I made a PR instead of pushing directly to check with you and discuss the structure of it with you first.

### CODE REVIEW

**Comment by ben-251** [comment]
I love this structure (mainly cuz oop), but yeah here are a few changes I'd suggest (i'll push them rn)

1. I changed the variable "root" to "root_word", because I didn't get what that variable was meant to be doing, and i think root_word trades readability for inv(word length), which is always worth it
2. I added a colon to the string asking for user input because i thought it looked nicer that way

**Comment by Voklen** [comment]
I mean the only problem with long variable names is a decrease in readability, so make them as long as they need to be for readability (there's just a point at which they subtract from it)

**Comment by ben-251** [comment]
At which point it becomes a matter of describing objects with as much necessary detail as possible, because in those cases with names that are really long, it's probably just unnecessary information, or redundant words maybe. In either case, I doubt we'll ever have that problem in our code //that level of fanciness hurts

**Comment by ben-251** [comment]
I forgot to save before committing (i know, such a PRO-grammer). I'm making a new commit.

**Review by Voklen — COMMENTED** [review]
Okay, that all seems to be good now

**Pull request merged**
